# Generated by Django 5.0.4 on 2024-05-12 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='hospital',
        ),
        migrations.AddField(
            model_name='log',
            name='vaccine',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='logistics.vaccine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccine',
            name='value',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Refrigerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.hospital')),
            ],
        ),
        migrations.AddField(
            model_name='log',
            name='refrigerator',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='logistics.refrigerator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccine',
            name='refrigerator',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='logistics.refrigerator'),
            preserve_default=False,
        ),
    ]
