# Generated by Django 5.0.4 on 2024-05-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_user_remove_vaccine_hospital_log_vaccine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_system_admin',
            field=models.BooleanField(default=False),
        ),
    ]
