# Generated by Django 5.0.4 on 2024-05-12 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_user_is_system_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='vaccine',
        ),
        migrations.RemoveField(
            model_name='log',
            name='value',
        ),
        migrations.AddField(
            model_name='district',
            name='user',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='logistics.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='field_name',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='new_value',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='previous_value',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refrigerator',
            name='manufacturer',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refrigerator',
            name='model_id',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refrigerator',
            name='monitor_type',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refrigerator',
            name='monitor_working',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='refrigerator',
            name='regulator_type',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refrigerator',
            name='temp_monitor_installed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='refrigerator',
            name='vaccine_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='refrigerator',
            name='voltage_regulator_installed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='log',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.user'),
        ),
        migrations.DeleteModel(
            name='Vaccine',
        ),
    ]
