# Generated by Django 5.0.4 on 2024-05-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_remove_log_vaccine_remove_log_value_district_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refrigerator',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
