# Generated by Django 5.0.4 on 2024-05-12 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_refrigerator_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.user'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.district'),
        ),
        migrations.AlterField(
            model_name='log',
            name='refrigerator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.refrigerator'),
        ),
        migrations.AlterField(
            model_name='refrigerator',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.hospital'),
        ),
    ]
